apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mature-leopon-go 
  janus-idp.io/tekton: mature-leopon-go
  backstage.io/kubernetes-id: mature-leopon-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: mature-leopon-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  