apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mature-leopon-go
  janus-idp.io/tekton: mature-leopon-go
  backstage.io/kubernetes-id: mature-leopon-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: mature-leopon-go
resources: 
- deployment.yaml
- route.yaml
- service.yaml
